# Generated by Django 2.0.9 on 2019-11-04 01:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pañol',
            fields=[
                ('Nombre', models.CharField(max_length=200)),
                ('Cantidad', models.CharField(max_length=200)),
                ('Tipo', models.CharField(max_length=200)),
                ('Fecha', models.CharField(max_length=200)),
            ],
        ),
		
		migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=200)),
                ('Contraseña', models.CharField(max_length=200)),
            ],
        ),
    ]
   
