# Generated by Django 2.0.9 on 2019-11-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pañol', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='apellidos',
            new_name='Apellidos',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.AlterField(
            model_name='pañol',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='Contraseña',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
